name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: eifinger/setup-uv@v1
        with:
          version: '0.3.5'
      - name: Install dependencies
        run: uv sync --frozen --all-extras
      - name: Format with ruff
        run: ruff format --diff
      - name: Lint with riff
        run: ruff check --diff
      - name: Type check with pyright
        run: pyright
